"""empty message

Revision ID: 824f0d5fd05a
Revises: 0b4eaf0d561e
Create Date: 2024-08-19 15:25:37.170293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824f0d5fd05a'
down_revision: Union[str, None] = '0b4eaf0d561e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('quantity_players', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'quantity_players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quantity_players', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('account', 'quantity_players')
    # ### end Alembic commands ###
