"""empty message

Revision ID: f2cbc7d5c681
Revises: 3d84d3bd4500
Create Date: 2024-08-25 20:53:06.641286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cbc7d5c681'
down_revision: Union[str, None] = '3d84d3bd4500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suggested', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'chat_suggested')
    op.drop_column('users', 'bot_suggested')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('bot_suggested', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('chat_suggested', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'suggested')
    # ### end Alembic commands ###
