"""empty message

Revision ID: b996c5d8074a
Revises: 824f0d5fd05a
Create Date: 2024-08-19 15:26:40.113143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b996c5d8074a'
down_revision: Union[str, None] = '824f0d5fd05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('quantity_players', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'quantity_players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quantity_players', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('account', 'quantity_players')
    # ### end Alembic commands ###
